### ISSUE TITLE
Questions about the dataset

### ISSUE THREAD

**Issue by oyxy2019** [zjunlp/WKM#8]
We have uploaded the [dataset](https://huggingface.co/datasets/zjunlp/WKM_pair_data). You are welcome to use it!

If you need any more help, feel free to ask!

_Originally posted by @Rolnand in https://github.com/zjunlp/WKM/issues/4#issuecomment-2445963272_
            

你好，我使用您这里给出的dataset，去运行world_knowledge_build.py时，遇到了多处data的索引不匹配的问题，请问是代码没有更新，还是我数据集用错了呢，谢谢！

运行参数如下：
```
if __name__ == "__main__" :
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset_path", type=str, default="../dataset/WKM_pair_data/alfworld_rc_pair.json")
    parser.add_argument("--task", type=str, default="alfworld")
    parser.add_argument("--gen", type=str, default="task_knowledge")
    parser.add_argument("--model_name",type=str,default="mistral")
    parser.add_argument("--output_path", type=str, default="./store/alfworld_task_knowledge.json")
    args = parser.parse_args()
    main(args)

```

**Comment by GoooDte** [comment]
您好，能否麻烦您提供一下具体的报错信息

**Comment by oyxy2019** [comment]
你好，报错信息像这样：
代码1：
```
def get_trajectory(data):
    tra_rejected = ""
    tra_chosen = ""
    # for conv_r in data["rejected"]["conversations"]:
    for conv_r in data["rejected"]:
        if conv_r["value"].startswith("Observation:"):
            tra_rejected += conv_r["value"][:1000]+'\n'
        else:
            tra_rejected += conv_r["value"]+'\n'
    # for conv_c in data["chosen"]["conversations"]:
    for conv_c in data["chosen"]:
        if conv_c["value"].startswith("Observation:"):
            tra_chosen += conv_c["value"][:1000]+'\n'
        else:
            tra_chosen += conv_c["value"]+'\n'
    return tra_rejected,tra_chosen
```
报错：
```
all process 335 datas
Processing data:   0%|          | 0/335 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/yinkh/linyy/llm/WKM/src/world_knowledge_build.py", line 118, in <module>
    main(args)
  File "/home/yinkh/linyy/llm/WKM/src/world_knowledge_build.py", line 105, in main
    task_knowledge_gen(data,output_path,model_name,args.task)
  File "/home/yinkh/linyy/llm/WKM/src/world_knowledge_build.py", line 53, in task_knowledge_gen
    tra_r,tra_c= get_trajectory(d)
  File "/home/yinkh/linyy/llm/WKM/src/world_knowledge_build.py", line 36, in get_trajectory
    for conv_r in data["rejected"]["conversations"]:
TypeError: list indices must be integers or slices, not str
```
代码2：
```
def get_alfworld_example(data):
    for k,v in alfworld_example.items():
        if k in data["game_file"]:
            return v
```
报错：
```
Traceback (most recent call last):
  File "/home/yinkh/linyy/llm/WKM/src/world_knowledge_build.py", line 120, in <module>
    main(args)
  File "/home/yinkh/linyy/llm/WKM/src/world_knowledge_build.py", line 107, in main
    task_knowledge_gen(data,output_path,model_name,args.task)
  File "/home/yinkh/linyy/llm/WKM/src/world_knowledge_build.py", line 57, in task_knowledge_gen
    example = get_alfworld_example(d["chosen"])
  File "/home/yinkh/linyy/llm/WKM/src/world_knowledge_build.py", line 26, in get_alfworld_example
    if k in data["game_file"]:
TypeError: list indices must be integers or slices, not str
```

正如上述提到的，加载json文件后，提取相关键值时，提示data["xxxx"]找不到，似乎代码处理的数据格式与dataset提供的数据不一致

辛苦您能解答一下，非常感谢！

**Comment by Rolnand** [comment]
我们刚刚更新了hf中的内容,麻烦您尝试一下https://huggingface.co/datasets/zjunlp/WKM_pair_data/tree/main 里的最新的alfworld_rc_pair.json,

**Comment by oyxy2019** [comment]
好的，我再试试，谢谢！

**Comment by oyxy2019** [comment]
你好，使用hf新上传的dataset之后，问题解决了，再次感谢！
